### ISSUE TITLE
Add support for customizing `jet-error-buffer-name`

### ISSUE THREAD

**Issue by danielhvs** [ericdallo/jet.el#8]
In my workflow I'd like to control `jet-error-buffer-name` var so that I can just see the error in stdout.
I propose to either:

1) Add an example like the below in the README.md to show off this possibility
```elisp
(use-package jet
  :custom
  (jet-error-buffer-name nil))
```

2) Or make it customizable, like so:

```elisp
(defcustom jet-error-buffer-name "*jet error*"
  "When `nil`, redirects to stdout"
  :group 'jet
  :type 'string)
```

**Comment by ericdallo** [comment]
Added the defcustom [here](https://github.com/ericdallo/jet.el/commit/35c2c0635755791ae1530cb7fb1feb1f949196c8)

**Comment by danielhvs** [comment]
Thanks, @ericdallo!
